apiVersion: apps/v1
kind: Deployment
metadata:
  name: puteklis-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puteklis-api
  template:
    metadata:
      labels:
        app: puteklis-api
    spec:
      containers:
        - name: app
          image: puteklis-api:dev
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: puteklis-api-config
            - secretRef:
                name: puteklis-api-secret
